//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.05 at 01:46:16 AM AST 
//


package com.outsidethebox.etl.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.outsidethebox.etl.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FlatFile_QNAME = new QName("", "FlatFile");
    private final static QName _PropertyFile_QNAME = new QName("", "PropertyFile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.outsidethebox.etl.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Declartion }
     * 
     */
    public Declartion createDeclartion() {
        return new Declartion();
    }

    /**
     * Create an instance of {@link ETL }
     * 
     */
    public ETL createETL() {
        return new ETL();
    }

    /**
     * Create an instance of {@link Declartion.Properties }
     * 
     */
    public Declartion.Properties createDeclartionProperties() {
        return new Declartion.Properties();
    }

    /**
     * Create an instance of {@link RESTFulWebservice }
     * 
     */
    public RESTFulWebservice createRESTFulWebservice() {
        return new RESTFulWebservice();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link SOAPWebservice }
     * 
     */
    public SOAPWebservice createSOAPWebservice() {
        return new SOAPWebservice();
    }

    /**
     * Create an instance of {@link CSV }
     * 
     */
    public CSV createCSV() {
        return new CSV();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Declartion.Connections }
     * 
     */
    public Declartion.Connections createDeclartionConnections() {
        return new Declartion.Connections();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link ETL.Operations }
     * 
     */
    public ETL.Operations createETLOperations() {
        return new ETL.Operations();
    }

    /**
     * Create an instance of {@link Declartion.Properties.PropertyFile }
     * 
     */
    public Declartion.Properties.PropertyFile createDeclartionPropertiesPropertyFile() {
        return new Declartion.Properties.PropertyFile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FlatFile")
    public JAXBElement<Object> createFlatFile(Object value) {
        return new JAXBElement<Object>(_FlatFile_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PropertyFile")
    public JAXBElement<Object> createPropertyFile(Object value) {
        return new JAXBElement<Object>(_PropertyFile_QNAME, Object.class, null, value);
    }

}
