//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.05 at 01:46:16 AM AST 
//


package com.outsidethebox.etl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}Database" minOccurs="0"/>
 *         &lt;element ref="{}SOAPWebservice" minOccurs="0"/>
 *         &lt;element ref="{}RESTFulWebservice" minOccurs="0"/>
 *         &lt;element ref="{}CSV" minOccurs="0"/>
 *         &lt;element ref="{}File" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Process")
public class Process {

    @XmlElement(name = "Database")
    protected Database database;
    @XmlElement(name = "SOAPWebservice")
    protected SOAPWebservice soapWebservice;
    @XmlElement(name = "RESTFulWebservice")
    protected RESTFulWebservice restFulWebservice;
    @XmlElement(name = "CSV")
    protected CSV csv;
    @XmlElement(name = "File")
    protected File file;

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link Database }
     *     
     */
    public Database getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link Database }
     *     
     */
    public void setDatabase(Database value) {
        this.database = value;
    }

    /**
     * Gets the value of the soapWebservice property.
     * 
     * @return
     *     possible object is
     *     {@link SOAPWebservice }
     *     
     */
    public SOAPWebservice getSOAPWebservice() {
        return soapWebservice;
    }

    /**
     * Sets the value of the soapWebservice property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOAPWebservice }
     *     
     */
    public void setSOAPWebservice(SOAPWebservice value) {
        this.soapWebservice = value;
    }

    /**
     * Gets the value of the restFulWebservice property.
     * 
     * @return
     *     possible object is
     *     {@link RESTFulWebservice }
     *     
     */
    public RESTFulWebservice getRESTFulWebservice() {
        return restFulWebservice;
    }

    /**
     * Sets the value of the restFulWebservice property.
     * 
     * @param value
     *     allowed object is
     *     {@link RESTFulWebservice }
     *     
     */
    public void setRESTFulWebservice(RESTFulWebservice value) {
        this.restFulWebservice = value;
    }

    /**
     * Gets the value of the csv property.
     * 
     * @return
     *     possible object is
     *     {@link CSV }
     *     
     */
    public CSV getCSV() {
        return csv;
    }

    /**
     * Sets the value of the csv property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSV }
     *     
     */
    public void setCSV(CSV value) {
        this.csv = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link File }
     *     
     */
    public File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link File }
     *     
     */
    public void setFile(File value) {
        this.file = value;
    }

}
